// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcIQqSTfnM274GHhriA9iF35W0NwOEVvo',
    appId: '1:885128048277:web:50a367682325082a21759c',
    messagingSenderId: '885128048277',
    projectId: 'april-2nd-fd159',
    authDomain: 'april-2nd-fd159.firebaseapp.com',
    storageBucket: 'april-2nd-fd159.firebasestorage.app',
    measurementId: 'G-GYYJ164R2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzLzP9rEfzFZ6kUqt5ybekcYU7xDNkNu4',
    appId: '1:885128048277:android:d928abff5bbaf2e821759c',
    messagingSenderId: '885128048277',
    projectId: 'april-2nd-fd159',
    storageBucket: 'april-2nd-fd159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAHj6M4TGsckuYG4rkLFVHzDvrBH_qcs4',
    appId: '1:885128048277:ios:42b1f8eb83578e7921759c',
    messagingSenderId: '885128048277',
    projectId: 'april-2nd-fd159',
    storageBucket: 'april-2nd-fd159.firebasestorage.app',
    iosBundleId: 'com.example.classwork6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAHj6M4TGsckuYG4rkLFVHzDvrBH_qcs4',
    appId: '1:885128048277:ios:42b1f8eb83578e7921759c',
    messagingSenderId: '885128048277',
    projectId: 'april-2nd-fd159',
    storageBucket: 'april-2nd-fd159.firebasestorage.app',
    iosBundleId: 'com.example.classwork6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcIQqSTfnM274GHhriA9iF35W0NwOEVvo',
    appId: '1:885128048277:web:1bfa034eed78f58721759c',
    messagingSenderId: '885128048277',
    projectId: 'april-2nd-fd159',
    authDomain: 'april-2nd-fd159.firebaseapp.com',
    storageBucket: 'april-2nd-fd159.firebasestorage.app',
    measurementId: 'G-LSDQP5E22R',
  );
}
